jobs:
  update-winget:
    runs-on: 'windows-latest'
    steps:
      - uses: 'vedantmgoyal9/winget-releaser@main'
        with:
          identifier: 'Tatsh.BPMDetect'
          max-versions-to-keep: 1
          token: '${{ secrets.WINGET_TOKEN }}'
name: 'Publish to WinGet'
'on':
  release:
    types:
      - 'released'
